GET http://localhost:3006/note
###

POST http://localhost:3006/note
Content-Type: application/x-www-form-urlencoded

date=02/01/2021
&time=06:00 PM
&photo_url=https://picsum.photos/id/1024/300/200
&flock_size=40
&vocalization=vocalization value
&habitat_value=habitat value
&user_id=1
&behaviour=1
&behaviour=2
&behaviour=3
&behaviour=4
###

GET http://localhost:3006/note/5
###