GET http://localhost:3006/signup
###

POST http://localhost:3006/signup
Content-Type: application/x-www-form-urlencoded

email=example2@email.com
&password=password
###

GET http://localhost:3006/login
###

POST http://localhost:3006/login
Content-Type: application/x-www-form-urlencoded

email=wrong@email.com
&password=wrong
###

POST http://localhost:3006/login
Content-Type: application/x-www-form-urlencoded

email=example@email.com
&password=password
###

GET http://localhost:3006/logout
###

GET http://localhost:3006/
###

GET http://localhost:3006/note
###

POST http://localhost:3006/note
Content-Type: application/x-www-form-urlencoded

date=02/01/2021
&time=06:00 PM
&photo_url=https://picsum.photos/id/1024/300/200
&flock_size=40
&species=6
&user_id=1
&behaviour=1
&behaviour=2
&behaviour=3
&behaviour=4
###

GET http://localhost:3006/note/1
###

GET http://localhost:3006/note/1/edit
###